# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e8e734502d93d12fab8313752b3e44e40639196e47c17db2f585f5beb136839c21976d0328bcdb19b98e6bc014a55afcfcbc2fd11632abad7a481844dba5c36

test:
  secret_key_base: 4d3daa9003361d8a8abe305e9b9f6f6c8d695d334a66a0cff36589848034dbbeebb50577cad847aaccc7eb103952b26271cae392eb6569ecb642006f82917498

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
